import { useState, useEffect } from 'react';
import { AISuggestion } from '../services/aiService';

interface AIFeedbackModalProps {
  isOpen: boolean;
  onClose: () => void;
  feedback: string | null;
  isLoading: boolean;
  error: string | null;
  suggestion?: AISuggestion | null;
  onApplySuggestion?: (suggestion: AISuggestion) => void;
}

export function AIFeedbackModal({ isOpen, onClose, feedback, isLoading, error, suggestion, onApplySuggestion }: AIFeedbackModalProps) {
  const [applied, setApplied] = useState(false);

  // Reset applied state when modal opens
  useEffect(() => {
    if (isOpen) {
      setApplied(false);
    }
  }, [isOpen]);

  if (!isOpen) return null;

  const handleOverlayClick = (e: React.MouseEvent) => {
    if (e.target === e.currentTarget) {
      onClose();
    }
  };

  // Convert markdown-style formatting to HTML
  const formatFeedback = (text: string): string => {
    return text
      // Bold text
      .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
      // Line breaks
      .replace(/\n/g, '<br />')
      // Lists (basic)
      .replace(/- /g, '• ');
  };

  return (
    <div className="changelog-overlay" onClick={handleOverlayClick}>
      <div className="ai-feedback-modal">
        <div className="changelog-header">
          <div className="ai-feedback-header-content">
            <span className="ai-feedback-icon">✨</span>
            <h2>AI Feedback</h2>
          </div>
          <div className="ai-feedback-help">
            <span className="ai-feedback-help-text">How does this work?</span>
            <span className="ai-feedback-help-icon">?</span>
            <span className="ai-feedback-help-tooltip">
              This feedback is generated by Claude AI, which analyzes your OKR against
              best practices including: clear direction, measurability, alignment,
              and strategic focus.
              <br /><br />
              <strong>Privacy:</strong> Your data is not used to train AI models and is not
              stored permanently. Anthropic's API is SOC 2 Type II compliant.
            </span>
          </div>
          <button className="changelog-close" onClick={onClose}>
            &times;
          </button>
        </div>

        <div className="ai-feedback-content">
          {isLoading && (
            <div className="ai-feedback-loading">
              <div className="ai-feedback-spinner"></div>
              <p>Analyzing your OKR...</p>
            </div>
          )}

          {error && (
            <div className="ai-feedback-error">
              <p><strong>Error:</strong> {error}</p>
              <p className="ai-feedback-error-hint">
                Make sure you have set VITE_ANTHROPIC_API_KEY in your .env file.
              </p>
            </div>
          )}

          {feedback && !isLoading && !error && (
            <div
              className="ai-feedback-text"
              dangerouslySetInnerHTML={{ __html: formatFeedback(feedback) }}
            />
          )}

          {suggestion && !isLoading && !error && (
            <div className="ai-suggestion-section">
              <div className="ai-suggestion-header">
                <span className="ai-suggestion-icon">💡</span>
                <span className="ai-suggestion-title">Suggested Improvement</span>
              </div>
              <div className="ai-suggestion-content">
                <div className="ai-suggestion-target">
                  {suggestion.type === 'objective' ? 'Objective' : 'Key Result'}
                  {suggestion.area && ` (${suggestion.area})`}
                </div>
                <div className="ai-suggestion-comparison">
                  <div className="ai-suggestion-before">
                    <span className="ai-suggestion-label">Current</span>
                    <span className="ai-suggestion-value">{suggestion.original}</span>
                  </div>
                  <div className="ai-suggestion-arrow">→</div>
                  <div className="ai-suggestion-after">
                    <span className="ai-suggestion-label">Suggested</span>
                    <span className="ai-suggestion-value">{suggestion.proposed}</span>
                  </div>
                </div>
                <div className="ai-suggestion-reason">{suggestion.reason}</div>
              </div>
              {onApplySuggestion && !applied && (
                <button
                  className="ai-suggestion-apply-btn"
                  onClick={() => {
                    onApplySuggestion(suggestion);
                    setApplied(true);
                  }}
                >
                  Apply
                </button>
              )}
              {applied && (
                <div className="ai-suggestion-applied">
                  <span>✓</span> Applied successfully
                </div>
              )}
            </div>
          )}
        </div>

        <div className="ai-feedback-footer">
          <button className="submit-btn" onClick={onClose}>
            {applied ? 'Done' : 'Got it'}
          </button>
        </div>
      </div>
    </div>
  );
}
